### ISSUE TITLE
Neo4j Graph App can not re-install

### ISSUE THREAD

**Issue by lixuanxian** [neo4j-apps/neo4j-desktop#78] opened 2020-03-27 14:21 UTC
## Steps

1.  Install graph app https://localhost:9000
2. remove graph app 
3. repeat step 1, install again

> It can not always repeat, but when re-install failed,  it will always failed. 

## Error 
![image](https://user-images.githubusercontent.com/2293168/77764134-18571200-7077-11ea-9ce0-c57e4d26ca3e.png)

## Here are detail info
GraphApp Link :  https://graphxrnext.kineviz.com   (I use https://localhost:9000)
OS:  Mac OS 10.15.3
Neo4j desktop: 1.2.5  and  1.2.5-dev.4

## Cache do not be removed
I remove the graph app, but the cache resource do not be removed.
![image](https://user-images.githubusercontent.com/2293168/77765328-12fac700-7079-11ea-8c5a-7df1997ca302.png)

**Comment by akollegger** [comment] 2020-06-03 12:25
Cannot reproduce. Closing for now, but please re-open if you're still experiencing a problem @lixuanxian .

**Closed by akollegger** 2020-06-03 12:25 UTC
